spring:
  application:
    name: s3browser
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

app:
  upload:
    multipart-threshold-bytes: 16777216
    multipart-part-size-bytes: 8388608

server:
  port: 8080

